name: 07 - Using Expressions
run-name: 07 - Using Expressions | Debug - ${{ inputs.Debug}}
on:
    push:
    workflow_dispatch:
           inputs:
            Debug:
                type: boolean
                default: false
jobs:
    echo_Workflow:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: inputs.Debug == true
              run: |
                echo "Triggered by: ${{ github.event_name}}"
                #echo "Branch: ${{ github.ref}}"
                echo "Commit SHA: ${{ github.SHA}}"
                echo "Runner OS: ${{runner.os}}"

            - name: '[debug] Print when triggered from main'
              if : ${{ inputs.debug && github.ref ==  'refs/heads/main'}}
              run: |
                echo "I was triggered from main"

            - name : named Greeting
              run : echo "Hello, world"