name: DemoCICD Pipeline
on:
  push:
  workflow_dispatch:
    branches:
      - feature/*
      - develop*
      - main
    paths:
      - "force-app/**"

jobs:
  configuring_Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Nodejs
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 20.15.0
      - name: Cache dependencies
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm init
          npm install
          # npm ci
